### ISSUE TITLE
style gsimplecal

### ISSUE THREAD

**Issue by limelime** [limelime/cust-live-deb#184]
https://wiki.archlinux.org/index.php/GTK%2B#GTK.2B_3.x

**Comment by limelime** [comment]
https://github.com/ehazlett/.dotfiles/blob/master/linux/gtk-3.0-settings.ini

**Comment by limelime** [comment]
http://stackoverflow.com/questions/34507808/css-theming-of-gtkcalendar-marked-days

**Comment by limelime** [comment]
/root/.config/gtk-3.0/gtk.css
/root/.config/gtk-3.0/setting.ini

**Comment by limelime** [comment]
```css
GtkCalendar {
  margin: 4px;
  padding: 5px;
  outline-offset: -1px; }
  GtkCalendar:inconsistent {
    color: mix(#555,#eee,0.5); }
  GtkCalendar:selected, GtkCalendar:selected:focus, GtkCalendar:selected:hover, GtkCalendar:selected:insensitive {
    background-color: transparent;
    color: #f0544c; }
  GtkCalendar.view, GtkCalendar.view:focus, GtkCalendar.view:hover, GtkCalendar.view:insensitive, GtkCalendar.highlight, GtkCalendar.highlight:focus, GtkCalendar.highlight:hover, GtkCalendar.highlight:insensitive, GtkCalendar.header, GtkCalendar.header:focus, GtkCalendar.header:hover, GtkCalendar.header:insensitive, GtkCalendar.button, GtkCalendar.button:focus, GtkCalendar.button:hover, GtkCalendar.button:insensitive {
    background-color: transparent;
    background-image: none;
    border-width: 0;
    border-radius: 0; }
  GtkCalendar.button, GtkCalendar.button:focus, GtkCalendar.button:hover, GtkCalendar.button:insensitive {
    color: #fff;
    border-width: 0;
    box-shadow: none; }
  GtkCalendar.highlight {
    color: #f0544c; }
 
/* gnome-calendar */
.calendar-view {
  background-color: #fff;
  color: #333; }
```
